# These are supported funding model platforms

github: Simmak7
ko_fi: YOUR_KOFI_USERNAME
# patreon: # Replace with your Patreon username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# open_collective: # Replace with your Open Collective username
# custom: ['https://your-custom-link.com']
